// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: membership.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateMembership = `-- name: UpdateMembership :exec
UPDATE users
SET is_chirpy_red = $2
WHERE id = $1
`

type UpdateMembershipParams struct {
	ID          uuid.UUID
	IsChirpyRed sql.NullBool
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) error {
	_, err := q.db.ExecContext(ctx, updateMembership, arg.ID, arg.IsChirpyRed)
	return err
}
